version: '3.3'
services:
        db:
                image: mariadb:latest
                restart: always
                environment:
                        MYSQL_DATABASE: wordpressdb
                        MYSQL_USER: ashutosh
                        MYSQL_PASSWORD_FILE: /run/secrets/db_password
                        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
                volumes:
                        - ./database66:/var/lib/mysql
                secrets:
                        - db_root_password
                        - db_password

        wordpress:
                image: wordpress:latest
                restart: always
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_USER: ashutosh
                        WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
                        WORDPRESS_DB_NAME: wordpressdb
                volumes:
                        - ./html4:/var/www.html
                secrets:
                        - db_password
secrets:
         db_password:
                external: true
         db_root_password:
                external: true
